#include <array>
#include <expected>
#include <span>
#include <system_error>
#include <openssl/rand.h>
#include <openssl/evp.h>


// THIS CODE COMPLETELY GENERATED BY CLOUDE
// IT MAY NOT WORK AT ALL
// i made very little changes, not even fixed types to uintN_t

namespace aig{ //ai generated

struct CipherCtx {
    CipherCtx() : ptr(EVP_CIPHER_CTX_new()) {}
    ~CipherCtx() { if (ptr) EVP_CIPHER_CTX_free(ptr); }

    CipherCtx(CipherCtx const&) = delete;
    CipherCtx& operator=(CipherCtx const&) = delete;
    CipherCtx(CipherCtx&& o) noexcept : ptr(std::exchange(o.ptr, nullptr)) {}
    CipherCtx& operator=(CipherCtx&& o) noexcept { std::swap(ptr, o.ptr); return *this; }

    operator EVP_CIPHER_CTX*() { return ptr; }
    explicit operator bool() const { return ptr != nullptr; }
private:
    EVP_CIPHER_CTX* ptr = nullptr;
};

template<size_t N>
std::array<unsigned char, N> random_bytes() {
    std::array<unsigned char, N> buf;
    RAND_bytes(buf.data(), static_cast<int>(N));
    return buf;
}

class AesSession {
    CipherCtx encrypt_ctx;
    CipherCtx decrypt_ctx;

  public:
    // encrypt_iv and decrypt_iv must be swapped on the other end
    static tl::expected<AesSession, std::error_code> create(
        std::array<unsigned char, 32> const& key,
        std::array<unsigned char, 16> const& encrypt_iv,
        std::array<unsigned char, 16> const& decrypt_iv
    ) {
        AesSession s;
        if (!s.encrypt_ctx || !s.decrypt_ctx)
            return tl::unexpected(std::make_error_code(std::errc::not_enough_memory));

        if (!EVP_EncryptInit_ex(s.encrypt_ctx, EVP_aes_256_ctr(), nullptr,
                                key.data(), encrypt_iv.data()))
            return tl::unexpected(std::make_error_code(std::errc::invalid_argument));

        if (!EVP_DecryptInit_ex(s.decrypt_ctx, EVP_aes_256_ctr(), nullptr,
                                key.data(), decrypt_iv.data()))
            return tl::unexpected(std::make_error_code(std::errc::invalid_argument));

        return s;
    }

    // CTR mode: output size == input size, always
    // OpenSSL API requires `written` param but it will always equal in.size()
    std::error_code encrypt(std::span<unsigned char const> in, std::span<unsigned char> out) {
        if (out.size() < in.size())
            return std::make_error_code(std::errc::no_buffer_space);

        int written{}; // API ceremony, always == in.size() in CTR
        if (!EVP_EncryptUpdate(encrypt_ctx, out.data(), &written,
                               in.data(), static_cast<int>(in.size())))
            return std::make_error_code(std::errc::io_error);

        return {};
    }

    std::error_code decrypt(std::span<unsigned char const> in, std::span<unsigned char> out) {
        if (out.size() < in.size())
            return std::make_error_code(std::errc::no_buffer_space);

        int written{}; // human: added init to zero for both just in case 
        if (!EVP_DecryptUpdate(decrypt_ctx, out.data(), &written,
                               in.data(), static_cast<int>(in.size())))
            return std::make_error_code(std::errc::io_error);

        return {};
    }
}; // class aes session
}//nms aig
